import Nav from './components/Nav/Nav'
import Footer from './components/footer/Footer'
import Header from './components/header/Header'
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons :{
    icon : './images/ict_favicon.png'
  }
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Header />
        <Nav />
        {children}
        <Footer />
        </body>
    </html>
  )
}
